### ISSUE TITLE
Can I store a custom version of object_changes?

### ISSUE THREAD

**Issue by hashwin** [paper-trail-gem/paper_trail#1082]
When using paper_trail, is there a more efficient way to store object_changes? Especially for jsonb columns, a large amount of data is stored in the table as it stores the entire value of the field before and after the change was made, even if the change was one key in a large object.

Right now, when I send it to the view I am using Hashdiff (https://github.com/liufengyun/hashdiff) to find the specific things that were changed, but I have to run this every time a view is loaded, plus there is a large load on the db as the entire field change is stored every time - versions is by far my largest table.

Is there an option of storing the Hashdiff directly in the object_changes and dumping that into the view every time it is loaded? It would make things a lot faster and less load on the db.

**Comment by jaredbeck** [comment]
Hi Ashwin, 

> .. versions is by far my largest table.

The best way to manage table size is with `version_limit`, though it's not appropriate for all use cases.

> .. is there a more efficient way to store object_changes?

First, as you probably know, `object_changes` is an optional column, so you could just drop it.

Now, is there a more efficient way? From the perspective of disk space, yes, we could be storing a patch instead of full values. For example, if you updated `users.full_name` from 'Alice Anderson' to 'Alice Bowman', we could store 's/Anderson/Bowman'. (That's just an example, it's not a practical patch representation'). For very large strings this could save a few blocks on disk. (A typical block size is 4 kibibytes, so the string would need to be quite long, much longer than a person's name.)

I have two concerns about any change to what we store on disk. The first concern is that PT has to support two different formats, and de/serialization is already one of the most complicated parts of PT. Second, I'd want to see benchmarks showing that the change doesn't negatively impact the performance of A) queries like `where_object_changes`, or B) reification.

If you'd like to continue to work on this, I think the first thing we should discuss is your proposed patch format.

**Comment by jaredbeck** [comment]
> If you'd like to continue to work on this, I think the first thing we should discuss is your proposed patch format.

Is this something you are still working on? Want me to keep this open?

**Comment by seanlinsley** [comment]
Jared and I previously discussed this a bit here: https://github.com/paper-trail-gem/paper_trail/issues/1046

FWIW, I have it on my to-do list to give [logidze](https://github.com/palkan/logidze) a try, which only stores changes as opposed to the whole object, and relies on database triggers instead of ActiveRecord callbacks.

**Comment by jaredbeck** [comment]
Closed via https://github.com/paper-trail-gem/paper_trail/pull/1102, which introduces the ability to completely control the contents of the `object_changes` column. Will release in 9.2.
