### ISSUE TITLE
Override item_type in Versions table

### ISSUE THREAD

**Issue by srklonaris** [paper-trail-gem/paper_trail#1107]
Is it possible to override the `item_type` in the Versions table?  If it isn't I would like to add this as a feature suggestion.

**Comment by lorint** [comment]
In order to have the reification work properly, `item_type` needs to refer to a specific model type. Currently `item_type` and `item_id` are automatically built out by ActiveRecord using a has_many with a polymorphic association `as: :item` that gets set up in PaperTrail::ModelConfig#setup_associations.

I've been working on a [PR](https://github.com/paper-trail-gem/paper_trail/pull/1108) that causes a subclassed STI model name to be put in for `item_type`, but beyond that if you'd like to store something different then you could add custom columns to your versions table and then put an `#info_for_paper_trail` method in a controller.  This [SO](https://stackoverflow.com/questions/17970490/papertrail-info-for-paper-trail-outside-the-context-of-a-controller) describes those options a little further.

**Comment by jaredbeck** [comment]
> ..  if you'd like to store something different then you could add custom columns to your versions table and then put an #info_for_paper_trail method in a controller. 

See also documentation [Section 4.c. Storing Metadata](https://github.com/paper-trail-gem/paper_trail/tree/v9.1.1#4c-storing-metadata)
