### ISSUE TITLE
Is it correct set has_paper_trail directly in the ApplicationRecord?

### ISSUE THREAD

**Issue by betosalvador** [paper-trail-gem/paper_trail#1118]
Hello guys.

I would like my entire app have the paper_trail tracking feature.

So, I put the 'has_paper_trail' directly in the ApplicationRecord.

This could bring me some problem?

If I keep this, is there any way to disable the paper_trail on specifics models?

Thanks in advance!

**Comment by jaredbeck** [comment]
Per our [contributing guide][1], please ask usage questions on [StackOverflow][2].

Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub.

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md
