### ISSUE TITLE
Reverting changes without overwriting ones that came after?

### ISSUE THREAD

**Issue by walshyb** [paper-trail-gem/paper_trail#1128]
Hi! I have a project where when I restore a version, I only want to change the fields that were changed in that particular version to be reverted, and not undo the changes of different fields of versions that came after.

I have no issue of creating functionality that locally, but I feel like this would be something that PaperTrail already supports. I scanned the docs and the code for something along these lines, searched Google, and looked at past issues, but haven't found anything.

Did I miss it, or is this something that PaperTrail doesn't support?

**Comment by jaredbeck** [comment]
Per our [contributing guide][1], please ask usage questions on [StackOverflow][2].

Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub.

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by walshyb** [comment]
My questions is less of a "How do I?" and more of a "Does this exist at all?", but I asked on StackOverflow: https://stackoverflow.com/questions/51774748/is-it-possible-to-revert-version-changes-in-papertrail-without-overwriting-ones

**Comment by jaredbeck** [comment]
> My questions is less of a "How do I?" and more of a "Does this exist at all?" ..

We don't have enough volunteers to accept either type of question. If you have any suggestions of how to make this clearer in the documentation, please let me know, thanks.
