### ISSUE TITLE
Is there a way to wrap paper trail's persistence in a begin/rescue?

### ISSUE THREAD

**Issue by jdejong** [paper-trail-gem/paper_trail#1151]
So we are having an issue where sometimes persistence into our versions table fails, but the commit into the main table succeeds but because paper_trails method threw the exception up to the main save, it causes the method to throw an exception back to the caller. 

I looked through the documents and I am not seeing anything that references this. Is there any way to rescue, log and continue if version operations fail and not blow up the main save?

If not I think this would be a valuable feature (the problem for me is I am stuck on v5 until we get through some refactors as we move to Rails 5).

Thanks in advance,

Jonathan

**Comment by jaredbeck** [comment]
> Is there a way to wrap paper trail's persistence in a begin/rescue?

Hi Jonathan, 

Due to limited volunteer time, we can't answer questions like "Is there a way ...". We ask you to do that research yourself, or use [StackOverflow][1]. We can only accept feature proposals that have already done this research.

Generally speaking, I'm open to improvements around rescuing version errors. Please do come back with a more concrete proposal. Thanks!

[1]: https://stackoverflow.com/tags/paper-trail-gem
