### ISSUE TITLE
A simple method/wrapper to restore to a version.

### ISSUE THREAD

**Issue by abhinaykumar** [paper-trail-gem/paper_trail#1257]
**Is your feature suggestion related to a problem? Please describe.** 
**NO**

**Describe the solution you'd like to build**

I used `paper_trail` to build the version history feature where you can go back and forth to a version and while doing so I realized that there is no method/wrapper to restore to a version using `version_id` something like `Model.restore_to(version_id)` which will essentially find the version on the model, jump to the next one version and `reify` to bring back the changes as they were at the point of creating this version. 

Internally it would do something like: `Model.versions.find(version_id).next.reify(has_many: true)` to accomplish the same. I understand someone can just do this but having a simple wrapper on top would make it easier to understand and use.

**Describe alternatives you've considered**

As an alternative, I'm executing this line of code: `Model.versions.find(version_id).next.reify(has_many: true)` to accomplish the same.

**Comment by gurgelrenan** [comment]
Duplicated #1248

**Comment by abhinaykumar** [comment]
Hi @gurgelrenan thanks for the response. yeah it is pretty similar and I read it before creating this issue. My only point is, there is way to achieve what I’m proposing here but it’s not that intuitive to call next version and reify to restore the version. I spent almost three days to figure that out could be due to my lack of understanding with paper-trail but if library can provide a more user friendly way to achieve the same then it might help the newbie like me :)

**Comment by jaredbeck** [comment]
Hi Abhinay, thanks for the suggestion. Your explanation makes sense.

Regarding the proposed API, `Model.restore_to(version_id)`, a few things come to mind.

1. We no longer add PT methods directly to model classes. Instead, we can discuss `Model.paper_trail.restore_to`.
2. In the interest of having consistent terminology, I'd suggest we use the word "reify" rather than "restore".
3. Is it better to take a `Version` instance as an argument, or an ID?
4. The name of the new method should indicate the use of `next`.

Putting these thoughts together, we could discuss something like `Model.paper_trail.reify_next_after(version)`. This implies a sister method `reify_previous_before(version)`. I don't like the idea of having two methods that are so similar. We could consider something more general, like `Model.paper_trail.reify(version.next)`.

**Comment by abhinaykumar** [comment]
Hi @jaredbeck, 

You just argued and counter-argued the feature 😅  I really like how you explained the whole scenario. I agree that it probably doesn't justify adding a new method to solve a trivial use case. I was working on the versioning feature for [ClayCMS](https://github.com/keepworks/claycms) and it felt obvious to have such a method but I understand the use case is very limited. 

Maybe this could be explained just by having something on the doc. Also, I have a question for you, if you were to achieve the same then how would you go about doing it? assuming you have access to `version_id`. I'm asking you this question to understand and come up with a better solution for navigating through versions. 

Happy New Year!! and thank you for maintaining PaperTrail

**Comment by jaredbeck** [comment]
> You just argued and counter-argued the feature 😅

Yeah, just thinking out loud :)

> how would you go about doing it?

I think what you have already is best.

`Model.versions.find(version_id).next.reify(has_many: true)`

It's tempting to simplify to:

`Version.find(version_id).next.reify(has_many: true)`

but, this will not handle [custom version classes](https://github.com/paper-trail-gem/paper_trail/#6a-custom-version-classes)

> .. I understand the use case is very limited.

I expect that navigating forward and backward is a common use case, but .. yeah, I'd rather not add to the public API if it can already be done with a one-liner.

> Happy New Year!! and thank you for maintaining PaperTrail

You're welcome :) Best wishes to you too for 2021
