### ISSUE TITLE
cannot properly undelete an object deleted outside of paper_trail

### ISSUE THREAD

**Issue by estani** [paper-trail-gem/paper_trail#1263]
Undeleting an object whose delete event is not in paper_trail does not seem to be possible.

This involves creating a reify of the last known version + applying the object_changes to it.

If the object was not modified, i.e. only a `create` event exists, it is not possible to recreate the object, even though the whole information is stored in the DB.

could `object_changes` be used in this way by any means?

This looks promising, though not sure it will always work:
```ruby
deleted_obj = Model.new id: 123
changes = YAML.load(deleted_obj.versions.last.object_changes)
changes.each do |key, values|
  # could assert expected previous value:
  #    assert_equals deleted_obj.send(key), values.first
  deleted_obj.send "#{key}=", values.last
end
```

**Comment by tlynam** [comment]
Hi @estani, what do you think of making a script with our bug report template?  https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE/bug-report.md
I'm still pretty new to the gem but I thought we can `reify` any version as long as the `object` column is present.  Do you have the `object` column?  From what I understand, `reify` is only supported when the `object` column is present.

**Comment by estani** [comment]
Hi, that's the thing, the object column is not there.
When you create an object the object column is empty, since it represents the previous state of the object (which would be nil)
The `object_changes` column stores how to get from the previous state (`object` column) to the current state.
As long as paper_trail sees all changes, this works fine.
But as soon as a problem arise, e.g. object get deleted without triggering the callbacks, then it's hard to get the object back, although it shouldn't, since the information is afaict there.

Tried to write what I mean in the script.
[bug_report.rb.txt](https://github.com/paper-trail-gem/paper_trail/files/5326446/bug_report.rb.txt)
(Not sure where I should put the script though, can't upload `.rb` files...)

**Comment by tlynam** [comment]
Hi @estani, okay, I think I understand what you're saying.  When creating say a user, a version record is created.  This version record doesn't have the `object` column populated.  Then the user is deleted without going through ActiveRecord `destroy` so no version is created with the `object` column populated.  Now it's not possible to `reify` because there's only one version record and the `object` column is `nil`.

If this is true, is it possible to ensure when the record is deleted, that ActiveRecord `destroy` is used?  How is the recording being deleted?
