### ISSUE TITLE
Make `sibling_versions` public again?

### ISSUE THREAD

**Issue by AndrewSouthpaw** [paper-trail-gem/paper_trail#1264]
Thank you for your contribution!

Due to limited volunteers, issues that do not follow this template will be
closed without comment.

**Is your feature suggestion related to a problem? Please describe.**

We used to use `#sibling_versions`, which was made private in 11.0.0. It makes sense how it was made private because it was undocumented, but we found it very helpful to solve our problem.

**Describe the solution you'd like to build**

Make `#sibling_versions` public again and add docs for it.

**Describe alternatives you've considered**

We just implement our own version of `sibling_versions` locally in our codebase. 😄

**Comment by tlynam** [comment]
Hi @AndrewSouthpaw, thank you for bringing this up.

Hi @jaredbeck, I hope you're well.  Do you know why `sibling_versions` was made private?

**Comment by jaredbeck** [comment]
> Do you know why sibling_versions was made private?

I don't remember, but it probably seemed like it was not intended to be public, e.g. because of a lack of docs, as Andrew mentioned. There are many methods in PT that are "accidentally public". I often comment them with `# @api private`, and occasionally actually make them `private`, as (I think) in this case. 

What alternatives are there already? Is `version.item.versions` equivalent?

If we decide to make `sibling_versions` public, we'll need docs and tests. We also have the opportunity to discuss the method name. For example, "siblings" may be a little misleading because it might imply the omission of self?

**Comment by AndrewSouthpaw** [comment]
> For example, "siblings" may be a little misleading because it might imply the omission of self

Yeah, we were thrown by this as well. 😅  It took some investigation to figure that one out.

> What alternatives are there already? Is `version.item.versions` equivalent?

I haven't found one but I'm eager to hear suggestions. We specifically needed a way to find other versions belonging to this item *without* going through `.item`. This was because `item` becomes `nil` when the associated record has been deleted, and we're specifically providing a UI for users to browse and restore deleted versions.

I'd suggest something like `item_versions` perhaps, keeping with the naming convention of `item` pointing to the associated ActiveRecord?

I'd be happy to contribute a PR if that's something you want to give the green light on.

**Comment by jaredbeck** [comment]
> What alternatives are there already?

What about using `Version.where` directly?

```ruby
# given `version` is a `PaperTrail::Version`, for example
version.class.where(item: version.item)
```

- Pros: 
  - encourages familiarity with normal ActiveRecord methods
  - encourages familiarity with the PT tables and columns 
- Cons:
  - a special method in PT might be easier to discover?

**Comment by AndrewSouthpaw** [comment]
Hmm I think that doesn't quite work for versions that have a deleted item, unless I'm doing this wrong:

```
> v = Version.find(...)
> v.item_id
=> 1234
> v.item_type
=> "Thing"
> Version.where(item: v.item)
=> 0
> Version.where(item_id: v.item_id, item_type: v.item_type).count
=> 2
```

That isn't what I *expected*, so I wonder if there is something fiddly happening with Rails there...

As far as pros/cons, here's my $0.02. I do like the idea of encouraging familiarity with how PT works, but honestly until we ran into this issue I was content with not having familiarity with the implementation details of PT. I do see how it's a small ask, but as a common lay-user I was hunting for an API method that encapsulated I wanted, rather than leveraging the system's tables and columns.

**Comment by jaredbeck** [comment]
That's so weird that `item` would be `nil` when both `item_type` and `item_id` are present .. 😓

**Comment by AndrewSouthpaw** [comment]
That part I'd expect, as in this particular example, Thing ID 1234 is deleted from the database. These are versions for a deleted activerecord. It's just surprising that rails doesn't translate `where(item: v.item)` into `where(item_id: v.item_id, item_type: v.item_type)`. 🤷‍♂️

**Comment by jaredbeck** [comment]
To refresh my memory, it *does* translate as expected, unless `v.item` is nil.

```ruby
user = User.last
PaperTrail::Version.where(item: user)
# SELECT `versions`.* FROM `versions` WHERE `versions`.`item_type` = 'User' AND `versions`.`item_id` = ..
PaperTrail::Version.where(item: nil)
# SELECT `versions`.* FROM `versions` WHERE `versions`.`item_id` IS NULL ..
```

Makes sense. I guess that's why `sibling_versions` explicitly constructs the desired `where` clause, avoiding the use of `self.item`.

```ruby
def sibling_versions
  @sibling_versions ||= self.class.with_item_keys(item_type, item_id)
end
```

Given the subtlety of correctly constructing a `where` clause, I'd like to have something in the public API again for this purpose. We've discussed why the word "sibling" is misleading. Your suggestion, `item_versions` makes perfect sense. Please proceed with your PR.
