### ISSUE TITLE
How to create a version without actually saving the data?

### ISSUE THREAD

**Issue by unkn0wn-developer** [paper-trail-gem/paper_trail#1271]
Hi, 

I'm working on creating a post approval functionality.
Everything is working except one thing.
How do I create a version without actually saving the data on my posts table?

I use 
```
post.title = "AAAAA"
post.paper_trail.record_update(force: false, in_after_callback: false, is_touch: false)
```
this creates a new version but its contents don't include post.title="AAAAA" instead of that it creates a copy of the latest version.

**Comment by 100cube** [comment]
Hi,
Are you perhaps looking for [change sets](https://github.com/paper-trail-gem/paper_trail/blob/v11.1.0/README.md#3c-diffing-versions)?

**Comment by tlynam** [comment]
I don't know.  Can you use ActiveModel::Dirty somehow?  You would be able to set an attribute and before saving access the previous and current values.
https://api.rubyonrails.org/classes/ActiveModel/Dirty.html

**Comment by jaredbeck** [comment]
Per our [contributing guide][1], please ask usage questions on [StackOverflow][2].

Due to limited volunteer time, we can only accept bug reports and feature requests here on GitHub.

Once you create a question on StackOverflow, please feel free to comment here with the URL.

For instructions on how to file a bug report, please see our [issue template][3].

[1]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/CONTRIBUTING.md
[2]: https://stackoverflow.com/tags/paper-trail-gem
[3]: https://github.com/paper-trail-gem/paper_trail/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
