### ISSUE TITLE
Improve fetching reified class names for STI models

### ISSUE THREAD

**Issue by hschne** [paper-trail-gem/paper_trail#1332]
**Is your feature suggestion related to a problem? Please describe.**

We use PaperTrail on various models. One of them is a legacy model, where we use (abuse?) single table inheritance to separate callbacks, validations, and so forth into separate submodels. Let's call that model `Setting`, which has a column `name`. Name contains values such as `user_setting`, `team_setting`, and so on. 

We follow an approach similar to [the one outlined here](https://stackoverflow.com/a/23295546/2553104) to use STI using the names column to map underscored names (`user_setting`) to the actual class (`UserSetting`). Note that usually, STI columns  contain carmelized names.   

When destroying such a model and reifying it, the existing mechanism does not account for our  ̶a̶w̶e̶f̶u̶l̶ ̶h̶a̶c̶k̶ workaround, and we get an error: 

```ruby
setting = Setting.create(name: 'user_setting')
setting.destroy
setting.versions.last.reify # <- This fails with the wrong constant name 'user_setting'
```

The underlying issue is the implementation of `PaperTrails::Reifier`: 

```ruby
def version_reification_class(version, attrs)
  inheritance_column_name = version.item_type.constantize.inheritance_column
  inher_col_value = attrs[inheritance_column_name]
  class_name = inher_col_value.blank? ? version.item_type : inher_col_value
  class_name.constantize # <- This does not account for non-standard class names, such as underscored instead of camelized
end
```

**Describe the solution you'd like to build**

Instead of simply using `class_name.constantize` I suggest to take advantage of the mechanism Rails provides - calling `find_sti_class`: 

```ruby
def version_reification_class(version, attrs)
  clazz = version.item_type.constantize

  inheritance_column_name = clazz.inheritance_column
  inher_col_value = attrs[inheritance_column_name]
  return clazz if inher_col_value.blank?

  clazz.send(:find_sti_class, inher_col_value)
end
```

This allows users who use some non-standard form of STI to use PaperTrail, while keeping the existing functionality intact.

**Describe alternatives you've considered**

I realize that this is a _very_ specific problem to have. The obvious alternative is to just not have that problem and properly use STI. Unfortunately, we don't really have that option :shrug: 

I'm of course perfectly fine with just monkey-patching `PaperTrail::Reifier` to suit our needs. However, I can't see any obvious downside to using `find_sti_class`, and this change makes reifying more flexible. 

Let me know what you think :)

**Comment by aried3r** [comment]
Hey @hschne!

I'm not super familiar with STI but it seems like a reasonable proposal as from a quick glance it seems to more closely resemble what Rails is doing. I'm not sure what paper_trail's stance on using Rails private APIs is (I mean, it _does_ use Arel, which I believe is still considered a private API). Is it necessary to call `find_sti_class` or could we also get away with, [starting with Rails 6.1, to use `sti_class_for`](https://github.com/rails/rails/pull/37500)?

`find_sti_class` seems to have some extra logic around it that I don't fully grasp, but I'd prefer using public APIs, if possible.

We also need to be careful, since in the past changes to STI broke other functionality. See https://github.com/paper-trail-gem/paper_trail/pull/1108, reasons and references why it was reverted in https://github.com/paper-trail-gem/paper_trail/pull/1143.

Somebody else has also mentioned the use of `find_sti_class` in the past here: https://github.com/paper-trail-gem/paper_trail/issues/1261.

**Comment by hschne** [comment]
Thanks for getting back to me so quickly. I did not know about `sti_class_for`, but at first glance it seems to be reasonable to use that instead instead of calling `find_sti_class` :+1: 

I agree that STI has proven problematic in the past, thanks for linking all those issues. However, those appear to be referring to much more significant changes. This should really just affect reifying STI models.

#1261 seems to be a pretty exact duplicate of this issue, pity it was closed :grin: 

@aried3r If you are still okay with giving this a go, I'd be happy to open a PR

**Comment by aried3r** [comment]
I'd be happy to see this in a PR. Ideally, if it's not too much work, could you commit a failing test case and then a commit that fixes it so we can see a nice red-green process? Even if we then have to squash it afterwards, as per the [pull request template](https://github.com/paper-trail-gem/paper_trail/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

It would definitely help me review it, since the CI setup is much more intricate than what I've got locally.
